name = "evergreen-invitation"
compatibility_date = "2025-09-27"
type = "javascript"

[build]
command = "npm run build"
cwd = "./"

[env.production]
name = "evergreen-invitation-prod"
route = "https://invitations.uz/*"

# Assets configuration for static site hosting
assets = { directory = "dist" }

observability = { enabled = true }

[env.staging]
assets = { directory = "dist" }
